---
stages:
  - build-image

variables:
  DOCKER_EMAIL: gitlab@antoinelegrand.me
  DOCKER_USERNAME: gitlab-ci-token
  DOCKER_PASSWORD: $CI_BUILD_TOKEN
  REGISTRY: registry.gitlab.com/${{cookiecutter.project_repo}}
  REGISTRY_HOST: registry.gitlab.com


cache:
  key: "$CI_PROJECT_ID"
  untracked: true

build_image:
  stage: build-image
  only:
    - tags
    - master
  script:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"  $REGISTRY_HOST
    - docker build --no-cache -t $REGISTRY:$CI_BUILD_REF_NAME .
    - docker push $REGISTRY:$CI_BUILD_REF_NAME
  tags:
    - kubespray
    - shell
