---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: {{cookiecutter.project_slug}}
  name: {{cookiecutter.project_slug}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: {{cookiecutter.project_slug}}
    spec:
      containers:
        - name: {{cookiecutter.project_slug}}
          image: {{image}}
          imagePullPolicy: Always
          command:
            - gunicorn
            - {{cookiecutter.project_slug}}.api.wsgi:app
            - -b
            - :5000
            - --threads
            - "1"
            - -w
            - "4"
            - --timeout
            - "240"
          ports:
            - name: {{cookiecutter.project_slug}}
              protocol: TCP
              containerPort: 5000
          livenessProbe:
            httpGet:
              path: /version
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 30
